const assert = require('node:assert/strict');
const {test} = require('node:test');
const {loadSourceModule:load} = require('../tests/helpers/load-source-module.cjs');
const content=load('src/content/idea-to-playable.js',['bootcampCourse','firstBootcampCohort']);
const model=load('src/lib/learning-courses.js',['cleanCourse','publicCourse','cleanCourseModules','cleanCourseResources','cleanCourseSessions','cleanCourseSubmission','cleanCourseAssessment','courseSeatCount','courseUsesSeat','courseUrl','courseError','COURSE_ACCESS_STATES'],{stripImports:true,sandbox:content});
const visibility=load('src/lib/content-visibility.js',['isPublicLearningStatus']);
const items=load('src/lib/learning-items.js',['cleanLearningItem','toPublicLearningItemDto','validateEnrollmentAnswers','isActiveEnrollmentState','ACTIVE_ENROLLMENT_STATES'],{stripImports:true,sandbox:{...model,...visibility}});
const dates=load('src/lib/course-dates.js',['courseLocalDate','courseUtcDate']);
function memoryDb(initial={}) {
 const records=new Map(Object.entries(structuredClone(initial)));let serial=Promise.resolve(),seq=0;
 const ref=path=>({path,id:path.split('/').pop(),get:async()=>({exists:records.has(path),id:path.split('/').pop(),data:()=>structuredClone(records.get(path)),ref:ref(path)})});
 function query(name,filters=[],order=null,max=Infinity){return{where:(field,op,value)=>query(name,[...filters,[field,value]],order,max),orderBy:field=>query(name,filters,field,max),limit:count=>query(name,filters,order,count),get:async()=>{let paths=[...records.keys()].filter(p=>p.startsWith(`${name}/`)&&filters.every(([f,v])=>records.get(p)[f]===v));if(order)paths.sort((a,b)=>new Date(records.get(a)[order])-new Date(records.get(b)[order]));const docs=await Promise.all(paths.slice(0,max).map(p=>ref(p).get()));return{docs,size:docs.length,empty:!docs.length};}};}
 return{records,collection:name=>({...query(name),doc:id=>ref(`${name}/${id||++seq}`)}),runTransaction:action=>{const run=serial.then(async()=>{const writes=[];const result=await action({get:target=>target.get(),set:(target,data)=>writes.push(()=>records.set(target.path,structuredClone(data))),create:(target,data)=>writes.push(()=>{assert.ok(!records.has(target.path));records.set(target.path,structuredClone(data));}),update:(target,data)=>writes.push(()=>{assert.ok(records.has(target.path));records.set(target.path,{...records.get(target.path),...structuredClone(data)});})});writes.forEach(w=>w());return result;});serial=run.catch(()=>{});return run;}};
}
const now=new Date('2026-10-01T12:00:00Z');
function setup(){const item=structuredClone(content.firstBootcampCohort),db=memoryDb({[`learning_items/${item.id}`]:item});const service=load('src/lib/learning-enrollment.js',['createLearningEnrollment','cancelLearningEnrollment','confirmWaitlistOffer','processExpiredWaitlistOffers','enrollmentDocumentId'],{stripImports:true,sandbox:{...model,...items,adminDb:db,hasCommunityContentAccess:data=>data.activeMember===true,createProductNotification:async()=>{},enqueueEmailEventForUsers:async()=>{},trainingAssignmentId:(uid,type,id)=>`${uid}_${id}`,isTrainingAssignmentActive:()=>false,getLearningProductConfig:()=>({waitlistConfirmationHours:48})}});return{item,db,service,user:uid=>({uid,userData:{activeMember:true}})};}
test('pilot schedule and timezone conversion, including DST',()=>{const item=items.cleanLearningItem(content.firstBootcampCohort);assert.equal(item.capacity,8);assert.equal(item.sessions.length,5);for(const s of item.sessions){assert.match(dates.courseLocalDate(s.startsAt,item.timeZone),/T18:00$/);assert.equal(new Date(s.endsAt)-new Date(s.startsAt),7200000);}assert.equal(dates.courseUtcDate('2026-10-26T18:00','Europe/Skopje'),'2026-10-26T17:00:00.000Z');assert.throws(()=>dates.courseUtcDate('2026-03-29T02:30','Europe/Skopje'),/does not exist/);});
test('public projections never expose private session or resource URLs',()=>{const course=model.cleanCourse({...content.bootcampCourse,resources:[{id:'r',title:'Recording',kind:'recording',url:'https://example.com/private',approved:true}]});assert.doesNotMatch(JSON.stringify(model.publicCourse(course)),/example.com/);course.resources[0].approved=false;assert.equal(model.publicCourse(course).resources.length,0);const item=structuredClone(content.firstBootcampCohort);item.sessions[0].privateSessionUrl='https://meet.example/private';assert.doesNotMatch(JSON.stringify(items.toPublicLearningItemDto(item)),/meet.example|privateSessionUrl|invitedUserIds/);});
test('concurrent requests cap physical seats at eight while allowing unlimited online enrollment',async()=>{const{db,item,service,user}=setup();const results=await Promise.all(Array.from({length:52},(_,i)=>service.createLearningEnrollment({itemId:item.id,user:user(`u${i}`),attendanceMode:i<12?'in_person':'online',db,now})));assert.equal(results.filter(r=>r.state==='confirmed'&&r.attendanceMode==='in_person').length,8);assert.equal(results.filter(r=>r.state==='waitlisted').length,4);const saved=db.records.get(`learning_items/${item.id}`);assert.equal(saved.onlineConfirmedCount,40);assert.equal(saved.confirmedCount,48);assert.equal(items.toPublicLearningItemDto(saved).placesRemaining,0);await assert.rejects(service.createLearningEnrollment({itemId:item.id,user:user('u0'),db,now}),/already have/);});
test('members and invited team can enroll, non-members cannot; course disable is enforced',async()=>{const{db,item,service,user}=setup();await assert.rejects(service.createLearningEnrollment({itemId:item.id,user:{uid:'outsider',userData:{}},db,now}),/not available/);db.records.get(`learning_items/${item.id}`).invitedUserIds=['team'];assert.equal((await service.createLearningEnrollment({itemId:item.id,user:{uid:'team',userData:{}},db,now})).state,'confirmed');db.records.set(`learning_courses/${item.courseId}`,{status:'draft',memberAccess:true});await assert.rejects(service.createLearningEnrollment({itemId:item.id,user:user('member'),db,now}),/not available/);});
test('online cancellation preserves physical seats; physical cancellation reserves and confirms next waitlisted',async()=>{const{db,item,service,user}=setup();for(let i=0;i<9;i++)await service.createLearningEnrollment({itemId:item.id,user:user(`p${i}`),db,now});await service.createLearningEnrollment({itemId:item.id,user:user('online'),attendanceMode:'online',db,now});await service.cancelLearningEnrollment({itemId:item.id,userId:'online',db,now});assert.equal(db.records.get(`learning_items/${item.id}`).reservedCount,0);await service.cancelLearningEnrollment({itemId:item.id,userId:'p0',db,now});assert.equal(db.records.get(`learning_items/${item.id}`).reservedCount,1);await service.confirmWaitlistOffer({itemId:item.id,userId:'p8',db,now});const saved=db.records.get(`learning_items/${item.id}`);assert.equal(saved.confirmedCount,8);assert.equal(saved.waitlistCount,0);assert.equal(saved.reservedCount,0);await assert.rejects(service.confirmWaitlistOffer({itemId:item.id,userId:'p8',db,now}),/expired/);});
test('expired offer releases reservation and offers the next person',async()=>{const{db,item,service,user}=setup();for(let i=0;i<10;i++)await service.createLearningEnrollment({itemId:item.id,user:user(`p${i}`),db,now});await service.cancelLearningEnrollment({itemId:item.id,userId:'p0',db,now});await service.processExpiredWaitlistOffers({db,now:new Date('2026-10-03T13:00:00Z')});assert.equal(db.records.get(`learning_enrollments/${service.enrollmentDocumentId(item.id,'p8')}`).waitlistOfferStatus,'expired');assert.equal(db.records.get(`learning_enrollments/${service.enrollmentDocumentId(item.id,'p9')}`).waitlistOfferStatus,'offered');assert.equal(db.records.get(`learning_items/${item.id}`).reservedCount,1);});
test('badge requires published itch.io game, ten verified ratings, and all competencies',()=>{const submission=model.cleanCourseSubmission({prototypePublished:true,finalUrl:'https://student.itch.io/game'});const assessment={approved:true,reviewCount:10,evidenceVerified:true,competencies:{scope:true,build:true,debug:true,version:true,ship:true}};assert.equal(model.cleanCourseAssessment(assessment,submission).approved,true);for(const patch of[{reviewCount:9},{reviewCount:-1},{evidenceVerified:false},{competencies:{}}])assert.throws(()=>model.cleanCourseAssessment({...assessment,...patch},submission));assert.throws(()=>model.cleanCourseAssessment(assessment,{}));for(const finalUrl of['https://itch.io.evil.example/game','javascript:alert(1)','https://user:password@student.itch.io/game'])assert.throws(()=>model.cleanCourseSubmission({finalUrl}));});
test('coursework persists submissions, gates recordings after expiry, and restricts assessment to managers',async()=>{const{db,item,service,user}=setup();const member=user('student');await service.createLearningEnrollment({itemId:item.id,user:member,db,now});const enrollmentRef=db.collection('learning_enrollments').doc(service.enrollmentDocumentId(item.id,member.uid));const course={...content.bootcampCourse,resources:[{id:'r',kind:'recording',approved:true,url:'https://example.com/recording'},{id:'draft',kind:'recording',approved:false,url:'https://example.com/draft'},{id:'g',kind:'guide',approved:true,url:'https://example.com/guide'}]};let actor=member;const route=load('src/app/api/learning-items/[slug]/coursework/route.js',['GET','PUT','PATCH'],{stripImports:true,sandbox:{...model,adminDb:db,Response,getRequestUser:async()=>actor,enrollmentDocumentId:service.enrollmentDocumentId,createProductNotification:async()=>{},loadCourseContext:async()=>({item,course,manager:actor?.admin,enrollment:db.records.get(enrollmentRef.path),enrollmentRef,enrolled:actor?.uid===member.uid,member:actor?.userData?.activeMember===true,internal:false})}});const params={params:Promise.resolve({slug:item.slug})};assert.equal((await(await route.GET({},params)).json()).resources.length,2);actor={...member,userData:{}};const expired=await(await route.GET({},params)).json();assert.equal(expired.recordingAccess,false);assert.equal(expired.resources.length,1);const submission={prototypePublished:true,finalUrl:'https://student.itch.io/game',completedDays:[1,2,3,4,5]};assert.equal((await route.PUT({json:async()=>submission},params)).status,200);const assessment={userId:member.uid,submissionVersion:1,approved:true,reviewCount:10,evidenceVerified:true,competencies:{scope:true,build:true,debug:true,version:true,ship:true}};assert.equal((await route.PATCH({json:async()=>assessment},params)).status,403);actor={uid:'teacher',admin:true};assert.equal((await route.PATCH({json:async()=>({...assessment,submissionVersion:0})},params)).status,409);assert.equal((await route.PATCH({json:async()=>assessment},params)).status,200);assert.ok(db.records.get(enrollmentRef.path).badge);actor=member;assert.equal((await route.PUT({json:async()=>submission},params)).status,409);actor={uid:'teacher',admin:true};assert.equal((await route.PATCH({json:async()=>({...assessment,approved:false})},params)).status,200);assert.equal(db.records.get(enrollmentRef.path).badge,null);actor={uid:'outsider',userData:{}};assert.equal((await route.GET({},params)).status,403);actor=null;assert.equal((await route.GET({},params)).status,401);});
test('price waitlist requires consent, deduplicates requests, and supports withdrawal',async()=>{const db=memoryDb();let actor={uid:'student',email:'student@example.com'};const route=load('src/app/api/learning-courses/[slug]/interest/route.js',['POST','DELETE'],{stripImports:true,sandbox:{adminDb:db,getRequestUser:async()=>actor,...content,Response}});const params={params:Promise.resolve({slug:content.bootcampCourse.slug})};assert.equal((await route.POST({json:async()=>({})},params)).status,400);for(let i=0;i<2;i++)assert.equal((await route.POST({json:async()=>({consent:true})},params)).status,200);assert.equal(db.records.size,1);await route.DELETE({},params);assert.equal([...db.records.values()][0].active,false);actor=null;assert.equal((await route.POST({json:async()=>({consent:true})},params)).status,401);});
