const { chromium } = require('playwright');
const { loadSourceModule: load } = require('../tests/helpers/load-source-module.cjs');
const assert = require('node:assert/strict');
const {bootcampCourse,firstBootcampCohort}=load('src/content/idea-to-playable.js',['bootcampCourse','firstBootcampCohort']);
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:3100/education/from-idea-to-playable',{waitUntil:'domcontentloaded'});
 await page.getByRole('heading',{name:'From Idea to Playable',exact:true}).waitFor();
 await page.getByRole('heading',{name:'Upcoming cohorts'}).waitFor();
 await page.getByRole('combobox').waitFor(); if(await page.getByRole('button',{name:'Reject All',exact:true}).count()) await page.getByRole('button',{name:'Reject All',exact:true}).click(); await page.screenshot({path:'tmp/bootcamp-desktop.png',fullPage:true});
 console.log('Public page rendered',await page.title());
 console.log('Live API status',await page.evaluate(async()=>{const r=await fetch('/api/learning-courses/from-idea-to-playable');return r.status;}));
 let enrolled=false,interested=false,submission={};
 const cohort=()=>({...firstBootcampCohort,location:'GOHQ + online',placesRemaining:8,eligibility:{allowed:true},enrollment:enrolled?{state:'confirmed',attendanceMode:'online'}:null});
 await page.route('**/api/learning-courses/from-idea-to-playable',r=>r.fulfill({json:{course:bootcampCourse,cohorts:[cohort()],authenticated:true,interested}}));
 await page.route('**/api/learning-courses/from-idea-to-playable/interest',async r=>{interested=r.request().method()==='POST';if(interested)assert.equal(r.request().postDataJSON().consent,true);await r.fulfill({json:{interested}});});
 await page.route(`**/api/learning-items/${firstBootcampCohort.slug}/enrollment`,async r=>{enrolled=r.request().method()==='POST';if(enrolled)assert.equal(r.request().postDataJSON().attendanceMode,'online');await r.fulfill({json:{enrollment:{state:enrolled?'confirmed':'canceled_by_participant'}}});});
 await page.route(`**/api/learning-items/${firstBootcampCohort.slug}/coursework`,async r=>{if(r.request().method()==='PUT'){submission=r.request().postDataJSON();return r.fulfill({json:{submission}});}return r.fulfill({json:{submission,modules:bootcampCourse.modules,sessions:firstBootcampCohort.sessions,resources:[],recordingAccess:false}});});
 await page.reload({waitUntil:'domcontentloaded'});
 await page.getByRole('combobox').selectOption('online');
 await page.getByRole('button',{name:'Enroll free',exact:true}).click();
 await page.getByText('Your enrollment is confirmed.',{exact:true}).waitFor();
 await page.getByLabel('Day 1 completed',{exact:true}).check();
 await page.getByLabel('My prototype is published and playable',{exact:true}).check();
 await page.getByLabel('itch.io game URL',{exact:true}).fill('https://student.itch.io/prototype');
 await page.getByLabel('Review evidence URL (jam ratings, comments, or screenshot)',{exact:true}).fill('https://itch.io/jam/go-test/rate/123');
 await page.getByRole('button',{name:'Save progress and evidence',exact:true}).click();
 await page.getByText('Progress and evidence saved. Your instructor will review your submission.',{exact:true}).waitFor();
 assert.deepEqual(submission.completedDays,[1]);assert.equal(submission.prototypePublished,true);
 await page.reload({waitUntil:'domcontentloaded'});
 await page.getByLabel('Day 1 completed',{exact:true}).waitFor();assert.equal(await page.getByLabel('Day 1 completed',{exact:true}).isChecked(),true);
 await page.getByLabel('Notify me about this course’s price and availability.',{exact:true}).check();
 await page.getByRole('button',{name:'Coming soon — join price waitlist',exact:true}).click();
 await page.getByRole('button',{name:'Leave waitlist',exact:true}).waitFor();
 await page.getByRole('button',{name:'Leave waitlist',exact:true}).click();
 await page.getByText('You left the price announcement waitlist.',{exact:true}).waitFor();
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'tmp/bootcamp-mobile.png',fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'No mobile horizontal overflow');
 await page.getByRole('button',{name:'Cancel enrollment',exact:true}).click();
 await page.getByText('Enrollment canceled. You may choose another attendance mode or cohort.',{exact:true}).waitFor();
 console.log('PASS: member UI enrollment, persisted coursework, expired-recording message, interest join/withdraw, cancellation and mobile layout (mock API).');
 console.log('Page errors:',JSON.stringify(errors));
 assert.equal(errors.length,0);
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
