"use client";

import { useCallback, useEffect, useState } from "react";
import { auth } from "@/firebase";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

const statuses = ["open", "in_progress", "waiting_on_member", "waiting_on_staff", "resolved", "closed"];
const date = (value) => value ? new Date(value).toLocaleString() : "";

export default function SupportOperationsPage() {
  const [tickets, setTickets] = useState([]); const [selectedId, setSelectedId] = useState(""); const [detail, setDetail] = useState(null); const [reply, setReply] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const request = useCallback(async (url, options = {}) => { const token = await auth.currentUser?.getIdToken(); const response = await fetch(url, { ...options, cache: "no-store", headers: { ...(options.headers || {}), Authorization: `Bearer ${token}` } }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result.error || "Support operation failed"); return result; }, []);
  const load = useCallback(async () => { const result = await request("/api/admin/support"); setTickets(result.requests || []); setSelectedId((current) => current || result.requests?.[0]?.id || ""); }, [request]);
  const loadDetail = useCallback(async (id) => { if (!id) return setDetail(null); setDetail(await request(`/api/admin/support?ticketId=${encodeURIComponent(id)}`)); }, [request]);
  useEffect(() => { const unsubscribe = auth.onAuthStateChanged(() => load().catch((error) => setMessage(error.message))); return unsubscribe; }, [load]);
  useEffect(() => { loadDetail(selectedId).catch((error) => setMessage(error.message)); }, [loadDetail, selectedId]);
  const act = async (action, payload = {}) => { setBusy(true); setMessage(""); try { await request("/api/admin/support", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ticketId: selectedId, action, ...payload }) }); setReply(""); setMessage("Support request updated and queued for Jira synchronization."); await load(); await loadDetail(selectedId); } catch (error) { setMessage(error.message); } finally { setBusy(false); } };
  return <div className="space-y-6"><div><h1 className="text-3xl font-bold">Support Operations</h1><p className="mt-2 text-muted-foreground">GO is the customer-facing record. Jira synchronization is an optional staff workflow adapter.</p></div>{message ? <p role="status" className="rounded-md border p-3 text-sm">{message}</p> : null}<div className="grid gap-6 xl:grid-cols-[360px_1fr]"><section className="space-y-2">{tickets.map((ticket) => <button key={ticket.id} onClick={() => setSelectedId(ticket.id)} className={`w-full rounded-md border p-3 text-left ${selectedId === ticket.id ? "border-primary bg-primary/5" : ""}`}><div className="flex justify-between gap-2"><span className="font-medium">{ticket.subject}</span><Badge variant="outline">{ticket.status.replaceAll("_", " ")}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{ticket.requesterEmail || ticket.requesterId} · {date(ticket.updatedAt)}</p></button>)}{tickets.length === 0 ? <p className="rounded-md border p-5 text-muted-foreground">No support requests.</p> : null}</section>{detail ? <Card><CardHeader><div className="flex flex-wrap items-start justify-between gap-4"><div><CardTitle>{detail.ticket.subject}</CardTitle><p className="mt-1 text-sm text-muted-foreground">{detail.ticket.category} · {detail.ticket.membershipTierAtCreation} · Jira {detail.ticket.jiraSyncStatus}{detail.ticket.jiraIssueKey ? ` (${detail.ticket.jiraIssueKey})` : ""}</p>{detail.ticket.jiraSyncError ? <p className="mt-1 text-xs text-destructive">{detail.ticket.jiraSyncError}</p> : null}</div><select aria-label="Support status" className="rounded-md border bg-background px-3 py-2" value={detail.ticket.status} onChange={(event) => act("set_status", { status: event.target.value })}>{statuses.map((status) => <option key={status} value={status}>{status.replaceAll("_", " ")}</option>)}</select></div></CardHeader><CardContent className="space-y-5"><div className="space-y-3">{detail.messages.map((item) => <div key={item.id} className="rounded-md border p-4"><div className="flex justify-between"><strong>{item.authorRole === "staff" ? "GO staff" : "Member"}</strong><span className="text-xs text-muted-foreground">{date(item.createdAt)}</span></div><p className="mt-2 whitespace-pre-wrap text-sm">{item.body}</p></div>)}</div><label className="block text-sm"><span className="mb-1 block font-medium">Staff reply</span><textarea className="min-h-24 w-full rounded-md border bg-background px-3 py-2" value={reply} onChange={(event) => setReply(event.target.value)} /></label><div className="flex flex-wrap gap-2"><Button disabled={busy || reply.trim().length < 2} onClick={() => act("reply", { message: reply })}>Reply</Button><Button disabled={busy} variant="outline" onClick={() => act("retry_jira")}>Retry Jira sync</Button></div></CardContent></Card> : <p className="rounded-md border p-6 text-muted-foreground">Select a support request.</p>}</div></div>;
}
