// Canonical reviewed runtime lesson copy. See starter-pathway.md for the editorial reference.
const lessons = [
  {
    "id": "notice",
    "world": 1,
    "slug": "notice",
    "title": "Notice",
    "promise": "Understand the repeating action inside a game.",
    "idea": "A game is a conversation between what the player does and what the rules do next.",
    "example": "Pick any familiar game and notice one small loop: choose, act, receive a result, choose again.",
    "mission": "Draw or describe one game loop in three to five steps.",
    "evidencePrompt": "A loop sketch, short written sequence, voice note, or photo of a paper diagram.",
    "reflectionPrompt": "What is the smallest action that makes this loop begin?",
    "badgeId": "signal-seeker",
    "badgeTitle": "Signal Seeker",
    "skillId": "observe-game-systems",
    "skillTitle": "Observe game systems",
    "missionXp": 50,
    "nextRouteKey": "imagine",
    "nextRouteLabel": "Imagine",
    "modes": [
      "drawing",
      "paper-prototype",
      "no-code",
      "level-editor",
      "game-engine",
      "programming"
    ],
    "access": "free"
  },
  {
    "id": "imagine",
    "world": 2,
    "slug": "imagine",
    "title": "Imagine",
    "promise": "Turn a large idea into a clear player experience.",
    "idea": "A strong game idea can be stated as what the player gets to do and feel.",
    "example": "“The player gets to sneak a tiny robot past sleeping machines.”",
    "mission": "Complete “The player gets to ___” and name one action the player takes.",
    "evidencePrompt": "The one-sentence player promise plus the chosen action.",
    "reflectionPrompt": "If only one thing remains playable, what should it be?",
    "badgeId": "idea-orbit",
    "badgeTitle": "Idea Orbit",
    "skillId": "define-player-experience",
    "skillTitle": "Define player experience",
    "missionXp": 50,
    "nextRouteKey": "shape",
    "nextRouteLabel": "Shape",
    "modes": [
      "drawing",
      "paper-prototype",
      "no-code",
      "level-editor",
      "game-engine",
      "programming"
    ],
    "access": "community"
  },
  {
    "id": "shape",
    "world": 3,
    "slug": "shape",
    "title": "Shape",
    "promise": "Shape a small, playable ruleset.",
    "idea": "Rules are promises about what can happen, what matters, and how the player learns the result.",
    "example": "In a tiny challenge, identify its goal, constraints, choice, feedback, and change.",
    "mission": "Write one goal, three rules, one meaningful choice, one feedback signal, and one thing that changes.",
    "evidencePrompt": "A rules card, diagram, paper prototype, or short design brief.",
    "reflectionPrompt": "Which rule creates a useful decision, and which part is only decoration?",
    "badgeId": "scope-scout",
    "badgeTitle": "Scope Scout",
    "skillId": "design-rules-and-scope",
    "skillTitle": "Design rules and scope",
    "missionXp": 75,
    "nextRouteKey": "build",
    "nextRouteLabel": "Build",
    "modes": [
      "drawing",
      "paper-prototype",
      "no-code",
      "level-editor",
      "game-engine",
      "programming"
    ],
    "access": "community"
  },
  {
    "id": "build",
    "world": 4,
    "slug": "build",
    "title": "Build",
    "promise": "Build a tiny playable version.",
    "idea": "A prototype is an experiment that lets someone experience the important part.",
    "example": "Compare a one-minute paper game or gray-box level with its larger imagined version. Notice what was removed.",
    "mission": "Make a loop that can be played in under five minutes. Remove anything that does not help the loop.",
    "evidencePrompt": "A playable prototype, paper game, screen recording, project file, or sequence of screenshots.",
    "reflectionPrompt": "What did you remove so the important action could be felt sooner?",
    "badgeId": "builder-spark",
    "badgeTitle": "Builder Spark",
    "skillId": "prototype-playable-systems",
    "skillTitle": "Prototype playable systems",
    "missionXp": 100,
    "nextRouteKey": "test",
    "nextRouteLabel": "Test",
    "modes": [
      "drawing",
      "paper-prototype",
      "no-code",
      "level-editor",
      "game-engine",
      "programming"
    ],
    "access": "community"
  },
  {
    "id": "test",
    "world": 5,
    "slug": "test",
    "title": "Test",
    "promise": "Learn what the game communicates without explaining it for the player.",
    "idea": "Playtesting turns another person’s actions into design information.",
    "example": "Watch a player pause, repeat an action, miss a signal, smile, ask a question, or find a surprising solution.",
    "mission": "Ask one person to try the prototype. Stay quiet for the first round. Record three observations and make one change.",
    "evidencePrompt": "Three observations plus the revision made in response.",
    "reflectionPrompt": "What did the player teach you that you could not have learned by staring at the prototype alone?",
    "badgeId": "playtest-oracle",
    "badgeTitle": "Playtest Oracle",
    "skillId": "observe-players-and-improve",
    "skillTitle": "Observe players and improve",
    "missionXp": 100,
    "nextRouteKey": "share",
    "nextRouteLabel": "Share",
    "modes": [
      "paper-prototype",
      "no-code",
      "level-editor",
      "game-engine",
      "programming"
    ],
    "access": "community"
  },
  {
    "id": "share",
    "world": 6,
    "slug": "share",
    "title": "Share",
    "promise": "Explain what you made, what you learned, and what happens next.",
    "idea": "Sharing is part of making: it helps another person understand the experiment and gives the work a next life.",
    "example": "A clear project note answers what it is, how to try it, what changed, and what the creator would do next.",
    "mission": "Write a creator note with Name / Play / Learn / Next, then attach a link, file, photo, or video if available.",
    "evidencePrompt": "A project page, presentation, creator note, or shareable prototype record.",
    "reflectionPrompt": "What is the smallest next step that would make this project more interesting?",
    "badgeId": "signal-sender",
    "badgeTitle": "Signal Sender",
    "skillId": "communicate-and-present",
    "skillTitle": "Communicate and present",
    "missionXp": 125,
    "nextRouteKey": "projects",
    "nextRouteLabel": "GO Projects",
    "modes": [
      "drawing",
      "paper-prototype",
      "no-code",
      "level-editor",
      "game-engine",
      "programming"
    ],
    "access": "community"
  }
];
export default lessons;
